import Footer from "@/components/user/footer/page";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/user/header/page";
import LayoutWebsite from "@/components/layout/LayoutWebsite";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title:
    "Couple TX - Thương hiệu thời trang Nam - Nữ hàng đầu Việt Nam – COUPLE TX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
